root -l -b -q plotRatioV2.C\(\"em\",\"eta1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"eta2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"pt1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"pt2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"njets\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"drll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"dphill\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"mll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"mth\",\"ggH_hww\"\)

root -l -b -q plotRatioV2.C\(\"me\",\"eta1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"eta2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"pt1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"pt2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"njets\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"drll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"dphill\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"mll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"mth\",\"ggH_hww\"\)

root -l -b -q plotRatioV2.C\(\"mm\",\"eta1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"eta2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"pt1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"pt2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"njets\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"drll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"dphill\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"mll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"mth\",\"ggH_hww\"\)

root -l -b -q plotRatioV2.C\(\"ee\",\"eta1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"eta2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"pt1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"pt2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"njets\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"drll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"dphill\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"mll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"mth\",\"ggH_hww\"\)


root -l -b -q plotRatioV2.C\(\"em\",\"eta1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"eta2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"pt1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"pt2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"njets\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"drll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"dphill\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"mll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"mth\",\"WW\"\)

root -l -b -q plotRatioV2.C\(\"me\",\"eta1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"eta2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"pt1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"pt2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"njets\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"drll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"dphill\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"mll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"mth\",\"WW\"\)

root -l -b -q plotRatioV2.C\(\"mm\",\"eta1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"eta2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"pt1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"pt2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"njets\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"drll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"dphill\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"mll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"mth\",\"WW\"\)

root -l -b -q plotRatioV2.C\(\"ee\",\"eta1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"eta2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"pt1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"pt2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"njets\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"drll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"dphill\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"mll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"mth\",\"WW\"\)


root -l -b -q plotRatioV2.C\(\"em\",\"eta1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"eta2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"pt1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"pt2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"njets\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"drll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"dphill\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"mll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"em\",\"mth\",\"top\"\)

root -l -b -q plotRatioV2.C\(\"me\",\"eta1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"eta2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"pt1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"pt2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"njets\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"drll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"dphill\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"mll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"me\",\"mth\",\"top\"\)

root -l -b -q plotRatioV2.C\(\"mm\",\"eta1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"eta2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"pt1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"pt2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"njets\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"drll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"dphill\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"mll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"mm\",\"mth\",\"top\"\)

root -l -b -q plotRatioV2.C\(\"ee\",\"eta1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"eta2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"pt1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"pt2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"njets\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"drll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"dphill\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"mll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"ee\",\"mth\",\"top\"\)


root -l -b -q plotRatioV2.C\(\"2j\",\"eta1\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"eta2\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"pt1\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"pt2\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"njets\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"drll\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"dphill\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"mll\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"mth\",\"qqH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"classvbf\",\"qqH_hww\"\)

root -l -b -q plotRatioV2.C\(\"2j\",\"eta1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"eta2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"pt1\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"pt2\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"njets\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"drll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"dphill\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"mll\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"mth\",\"ggH_hww\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"classvbf\",\"ggH_hww\"\)

root -l -b -q plotRatioV2.C\(\"2j\",\"eta1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"eta2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"pt1\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"pt2\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"njets\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"drll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"dphill\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"mll\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"mth\",\"top\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"classvbf\",\"top\"\)

root -l -b -q plotRatioV2.C\(\"2j\",\"eta1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"eta2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"pt1\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"pt2\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"njets\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"drll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"dphill\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"mll\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"mth\",\"WW\"\)
root -l -b -q plotRatioV2.C\(\"2j\",\"classvbf\",\"WW\"\)

